<?php

namespace Database\Seeders;

use App\Enums\ContentTier;
use App\Enums\ContentType;
use App\Enums\Language;
use App\Enums\SkillLevel;
use App\Models\ContentItem;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class EducationalContentSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::first() ?? User::factory()->create();

        $articles = [
            [
                'title' => 'Understanding Price-to-Earnings (P/E) Ratios on the PSX',
                'type' => ContentType::ARTICLE,
                'tier' => ContentTier::FREE,
                'skill_level' => SkillLevel::BEGINNER,
                'duration' => 6,
                'key_takeaways' => [
                    'P/E ratio measures how much investors are paying for every Rs. 1 of company net earnings.',
                    'A lower P/E (e.g. 4x - 7x) on PSX can indicate an undervalued bargain, but must be compared with sector peers.',
                    'Historically, the PSX KSE-100 trades at an average P/E of 6x–8x, a steep discount to regional emerging markets.',
                    'Always combine P/E with debt ratios and free cash flows before making an investment decision.',
                ],
                'quiz_data' => [
                    'question' => 'If a PSX stock is trading at PKR 120 per share and has an annual EPS of PKR 15, what is its P/E ratio?',
                    'options' => ['6.0x', '8.0x', '12.0x', '15.0x'],
                    'correct_index' => 1,
                    'explanation' => 'P/E = Market Price (PKR 120) / Earnings Per Share (PKR 15) = 8.0x. This means you are paying 8 times annual earnings.',
                ],
                'urdu_body' => "P/E Ratio (Price-to-Earnings) ka aasaan matlab yeh hai ke kisi company ke Rs. 1 saalana profit ke peechay aap stock market mein kitnay Rupay ada kar rahay hain.\n\nMisal ke tor par: Agar Fauji Fertilizer ka share price Rs. 120 hai aur saalana per-share profit (EPS) Rs. 15 hai, to P/E ratio hoga 120 / 15 = 8x. Is ka matlab aap 8 saal ke profit ke barabar qeemat de rahay hain.\n\nPSX par aam tor par P/E ratios dunya ke muqablay mein kafi saste hotay hain (4x se 7x). Lekin hamesha ek hi sector ki companies ka aapas mein muqabla karein, misal ke tor par MCB ka muqabla HBL se karein, cement company se nahi.",
                'body' => "The Price-to-Earnings (P/E) ratio is the single most widely referenced valuation metric for evaluating companies listed on the Pakistan Stock Exchange (PSX).\n\n### What Does P/E Tell You?\nAt its core, the P/E ratio tells you how many Rupees investors are willing to pay for every Rs. 1 of annual earnings generated by the business. It is calculated as:\n\nP/E Ratio = Current Market Price per Share / Earnings Per Share (EPS)\n\nFor example, if a blue-chip company like Engro Corporation is trading at PKR 300 per share and its audited trailing twelve-month earnings per share (EPS) is PKR 50, its P/E ratio is 300 / 50 = 6.0x.\n\n### Evaluating PSX P/E Multiples\nGlobally, emerging and frontier markets trade at P/E multiples between 12x and 20x. In contrast, the Pakistan Stock Exchange has historically traded at deep value multiples ranging between 4x and 8x.\n\nWhen evaluating a stock:\n1. **Peer Comparison**: Compare cement companies (Lucky Cement vs Pioneer Cement) within their own sector. Never compare a capital-heavy cement firm with a high-growth technology stock like Systems Limited.\n2. **Historical Mean**: Check if the stock is trading below or above its 5-year historical average multiple.\n3. **Quality of Earnings**: Ensure profits are backed by actual operating cash flows rather than one-time asset sales.",
            ],
            [
                'title' => 'Beginner\'s Guide to Mutual Funds & Income Funds in Pakistan',
                'type' => ContentType::ARTICLE,
                'tier' => ContentTier::FREE,
                'skill_level' => SkillLevel::BEGINNER,
                'duration' => 7,
                'key_takeaways' => [
                    'Mutual funds pool savings from thousands of retail investors under professional Fund Managers.',
                    'Money Market and Income Funds invest in Government T-Bills and bank deposits, providing stable monthly cash yields with minimal risk.',
                    'Equity Funds invest in PSX shares for higher long-term compounding over 3–5 year horizons.',
                    'You do not need a stock brokerage account; you can register directly via licensed Asset Management Companies (AMCs).',
                ],
                'quiz_data' => [
                    'question' => 'Which mutual fund category is ideal for an emergency savings fund requiring low volatility and quick withdrawals?',
                    'options' => ['High-Beta Equity Fund', 'Money Market / Cash Fund', 'Index Tracker Fund', 'Commodity Gold Fund'],
                    'correct_index' => 1,
                    'explanation' => 'Money Market funds invest in ultra-safe, short-term government treasury bills and bank deposits, offering stable daily/monthly yields and next-day liquidity.',
                ],
                'urdu_body' => "Mutual Funds aam Pakistani retail investor ke liye market mein dakhil hone ka sab se aasaan aur safe tareeqa hai.\n\nIs mein aap ko khud companies ki balance sheets check karne ki zaroorat nahi hoti, balkay professional Fund Managers (jaise Al Meezan, UBL Funds, MCB Funds) aap ka paisa mukhtalif stocks ya government T-Bills mein invest kartay hain.\n\nAgar aap safe monthly munafa chahtay hain to Money Market / Income Funds behtareen hain. Agar aap 5-10 saal ke liye daulat barhana chahtay hain to Equity Funds behtar hain.",
                'body' => "Mutual funds represent the most accessible entry point for everyday Pakistani salaried professionals, freelancers, and students wanting to beat inflation without managing individual stocks.\n\n### How Mutual Funds Work in Pakistan\nWhen you invest in an Asset Management Company (AMC) regulated by the Securities & Exchange Commission of Pakistan (SECP), your capital is pooled with other retail and institutional investors. A professional team of CFA charterholders and financial analysts manages the allocation.\n\n### The Major Fund Categories:\n1. **Money Market Funds (Low Risk)**: Invests in 3-month to 6-month Government Treasury Bills (T-Bills) and high-grade bank deposits. Great for emergency funds.\n2. **Income Funds (Low-to-Moderate Risk)**: Invests in government Pakistan Investment Bonds (PIBs) and corporate Sukuks for competitive regular yields.\n3. **Equity Funds (Moderate-to-High Risk)**: Invests directly in PSX KSE-100 listed equities like Meezan Bank, Hubco, and Lucky Cement. Built for long-term wealth creation (3–7 years).",
            ],
            [
                'title' => 'CDC Sub-Account vs Investor Account (IAS): Which One Do You Need?',
                'type' => ContentType::ARTICLE,
                'tier' => ContentTier::FREE,
                'skill_level' => SkillLevel::INTERMEDIATE,
                'duration' => 8,
                'key_takeaways' => [
                    'The Central Depository Company (CDC) acts as the electronic vault holding all Pakistani stock shares.',
                    'A Broker Sub-Account is opened automatically when you open a trading account with a licensed PSX brokerage.',
                    'A direct CDC Investor Account (IAS) provides maximum security because only you hold authorization to move or pledge shares.',
                    'Retail investors with long-term dividend portfolios frequently move long-term shares into direct IAS accounts for peace of mind.',
                ],
                'quiz_data' => [
                    'question' => 'What is the primary security advantage of holding long-term shares in a direct CDC Investor Account (IAS)?',
                    'options' => ['SECP pays you 20% annual guaranteed bonus', 'Shares are held directly in your name with CDC and cannot be moved or pledged by a broker', 'You never pay any brokerage commissions', 'Automatic exemption from dividend tax'],
                    'correct_index' => 1,
                    'explanation' => 'Direct CDC Investor Accounts ring-fence custody directly with the central depository, safeguarding your equity ownership even if a brokerage firm faces insolvency.',
                ],
                'urdu_body' => "PSX par shares khareednay ke baad aap ke shares physical certificates mein nahi, balkay electronic shakal mein Central Depository Company (CDC) ke paas mehfooz hotay hain.\n\nSub-Account: Yeh aap ka broker aap ke liye CDC system ke andar banata hai. Is ke zariye rozana buy/sell orders fast execute hotay hain.\n\nInvestor Account (IAS): Yeh direct CDC ke sath aap ka zati safe-deposit box hota hai. Broker is mein se aap ke shares ko aap ke direct SMS/Biometric authorization ke baghair hath nahi laga sakta. Long-term wealth ke liye IAS behtareen protection hai.",
                'body' => "Whenever you purchase shares of a Pakistani company like Meezan Bank (\$MEBL) or Oil & Gas Development Co (\$OGDC), you don't receive paper certificates. Instead, the Central Depository Company of Pakistan (CDC) records your ownership electronically.\n\n### The Two Types of Custody Accounts:\n\n#### 1. Broker Sub-Account\nWhen you open an online trading account with a licensed PSX broker (e.g., AKD, Arif Habib, JS Global), a sub-account is created under the broker's umbrella participant account. It is fast, convenient, and enables instantaneous electronic settlement through NCCPL.\n\n#### 2. CDC Investor Account (IAS)\nAn Investor Account is opened directly with CDC Pakistan (independent of any broker). Shares parked in your IAS cannot be pledged, transferred, or manipulated by any third party without your explicit direct authorization.\n\n### Recommended Best Practice:\nKeep your active trading capital in your broker sub-account. Once you build a substantial core position in dividend aristocrats that you plan to hold for 5+ years, transfer those shares to your CDC Investor Account for maximum structural safety.",
            ],
            [
                'title' => 'Demystifying the KSE-100 Index: Weighting & Heavyweights',
                'type' => ContentType::ARTICLE,
                'tier' => ContentTier::FREE,
                'skill_level' => SkillLevel::INTERMEDIATE,
                'duration' => 9,
                'key_takeaways' => [
                    'KSE-100 represents roughly 85% of total market capitalization of all listed companies on the PSX.',
                    'The index selection criteria includes the largest company from each of the 36 sectors, with remaining slots filled by market capitalization.',
                    'Commercial Banks, Fertilizers, and Exploration & Production (E&P) sectors drive over 50% of daily index points.',
                    'A green index day does not mean every stock went up — index heavyweights heavily sway the headline numbers.',
                ],
                'quiz_data' => [
                    'question' => 'Why can the KSE-100 index close up +600 points even when 60% of all listed companies closed in the red?',
                    'options' => ['SECP manually overrides index points on Mondays', 'The KSE-100 is market-cap weighted, meaning top companies like MCB, FFC, and OGDC have significantly more influence on the points than smaller companies', 'Only foreign institutions are counted in the points calculation', 'Mutual funds reset their balances every evening'],
                    'correct_index' => 1,
                    'explanation' => 'Because the KSE-100 is market-cap weighted, rallies in large-cap heavyweights (like banking and fertilizer giants) contribute more points than dozens of smaller companies falling.',
                ],
                'urdu_body' => "KSE-100 index Pakistan Stock Exchange ka markazi barometer hai. Jab aap news mein suntay hain ke 'PSX 1,000 points barh gayi', to is ka matlab KSE-100 index mein izafa hua hai.\n\nIndex mein har sector ki top company aur market cap ke lehaaz se sab se bari 100 companies shamil hoti hain.\n\nSab se ahem baat: 3 baray sectors (Banks, Fertilizer, aur Oil & Gas) pooray index ka 50% se zyada hissa hain. Agar banks aur fertilizer barh rahay hon to baqi choti companies girnay ke bawajood index green nazar aata hai.",
                'body' => "Every business headline in Pakistan reports the daily point change of the KSE-100 index. But what does that number actually measure?\n\n### Composition of the KSE-100\nThe KSE-100 was introduced in November 1991 with a base value of 1,000 points. Today, it reflects approximately 85% of the total market capitalization of all companies listed on the PSX.\n\nThe 100 companies are selected according to strict rules:\n- **Sector Leaders**: The company with the highest market capitalization from each of the 36 sectors is automatically inducted.\n- **Market Cap Ranking**: The remaining 64 spots are filled by the largest companies regardless of sector.\n\n### Understanding Sector Heavyweights\nBecause the index is market-capitalization weighted, not all 100 stocks carry equal weight. In fact, three sectors dictate more than half of the daily point swings:\n1. **Commercial Banks** (MCB, UBL, MEBL, HBL)\n2. **Fertilizer** (FFC, ENGRO, EFERT)\n3. **Oil & Gas Exploration** (OGDC, PPL, MARI)\n\nUnderstanding this dynamic prevents panic: when headlines scream about a 1,000-point fall, savvy retail investors check whether the drop was concentrated in a single sector due to a tax policy change or if the broader market remains fundamentally strong.",
            ],
            [
                'title' => 'Shariah-Compliant Stock Screening: How KMI-30 Separates Halal Equities',
                'type' => ContentType::ARTICLE,
                'tier' => ContentTier::FREE,
                'skill_level' => SkillLevel::ADVANCED,
                'duration' => 11,
                'key_takeaways' => [
                    'Core Business Screening: Core business activities must be Halal (no conventional interest-based banking, alcohol, gambling, or non-permissible entertainment).',
                    'Debt-to-Total Assets: Total interest-bearing debt must not exceed 37% of total assets.',
                    'Non-Compliant Investments: Interest-bearing investments must not exceed 33% of total assets.',
                    'Dividend Purification: Any minor incidental interest income must be calculated and donated to charity without tax deduction claims.',
                ],
                'quiz_data' => [
                    'question' => 'Under SECP and KMI-30 Shariah screening guidelines, what is the maximum permissible ratio of interest-bearing debt to total assets?',
                    'options' => ['0% (Zero debt permitted)', 'Less than 37%', 'Exactly 50%', 'Up to 75%'],
                    'correct_index' => 1,
                    'explanation' => 'KMI-30 guidelines allow a maximum threshold of less than 37% for interest-bearing debt relative to the company total assets.',
                ],
                'urdu_body' => "Pakistan Stock Exchange mein Islamic investments ke liye KMI-30 (KSE Meezan Index) banaya gaya hai.\n\nShariah Board 6 sakht usoolon ke tehat har 6 maah baad companies ki screening karta hai:\n1. Business Halal hona chahiye (Conventional Banks, Casino, Sharab shamil nahi).\n2. Interest-bearing qarza Total Assets ke 37% se kam hona chahiye.\n3. Haram zariya se aane wali aamdani (agar koi ho) ko Dividend Purification ke zariye charity mein dena zaroori hota hai.\n\nIs screening ki madad se aap ba-aasani Meezan Bank, Lucky Cement, Engro Corporation, aur Systems Limited jaisi Shariah-compliant companies mein invest kar saktay hain.",
                'body' => "For millions of Pakistani Muslims, participating in capital markets requires strict adherence to Islamic financial principles. The KSE-Meezan Index (KMI-30) was co-developed by Al-Meezan Investment Management and the PSX to track the performance of top Shariah-compliant equities.\n\n### The 6-Point Shariah Screening Framework\nA company must satisfy all six criteria established by reputable Shariah scholars and approved by the SECP:\n\n1. **Core Business Activity**: The core business must be permissible. Conventional interest-based commercial banks, life insurance providers, and gambling enterprises are categorically excluded.\n2. **Interest-Bearing Debt to Total Assets**: Total interest-bearing debt must be **less than 37%** of total assets.\n3. **Non-Compliant Investments to Total Assets**: Investments in conventional interest-bearing deposits, T-Bills, or bonds must be **less than 33%** of total assets.\n4. **Non-Compliant Income to Total Revenue**: Any incidental interest income earned on operational bank accounts must not exceed **5%** of total gross revenue.\n5. **Illiquid Assets to Total Assets**: At least **25%** of total assets must be tangible, illiquid assets (plant, machinery, inventory), ensuring the share represents an actual business interest rather than just currency trading.\n6. **Market Price vs Net Liquid Assets**: Market price per share must exceed net liquid assets per share.\n\n### Dividend Purification\nIf a Shariah-compliant firm earns 1% of its revenue from temporary cash parked in an interest-bearing account, Shariah guidelines require the investor to 'purify' their dividends by donating that exact 1% proportion to charity.",
            ],
        ];

        foreach ($articles as $item) {
            ContentItem::updateOrCreate(
                ['slug' => Str::slug($item['title'])],
                [
                    'title' => $item['title'],
                    'type' => $item['type'],
                    'tier' => $item['tier'],
                    'language' => Language::ENGLISH,
                    'skill_level' => $item['skill_level'],
                    'duration_minutes' => $item['duration'],
                    'key_takeaways' => $item['key_takeaways'] ?? null,
                    'quiz_data' => $item['quiz_data'] ?? null,
                    'urdu_body' => $item['urdu_body'] ?? null,
                    'body' => $item['body'],
                    'published_at' => now(),
                    'created_by' => $admin->id,
                ]
            );
        }
    }
}
